/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

public class MtcModPa implements MtcModPaConstants {
  public static int Mtc_ModPa_Register() {
    return MtcModPaJNI.Mtc_ModPa_Register();
  }

}
