/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.juphoon.cmcc.app.lemon;

public class MtcNumber {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MtcNumber(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MtcNumber obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MtcConfCmccJNI.delete_MtcNumber(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(int value) {
    MtcConfCmccJNI.MtcNumber_value_set(swigCPtr, this, value);
  }

  public int getValue() {
    return MtcConfCmccJNI.MtcNumber_value_get(swigCPtr, this);
  }

  public MtcNumber() {
    this(MtcConfCmccJNI.new_MtcNumber(), true);
  }

}
